### ISSUE TITLE
Error running demo code: forward() missing 1 required positional argument: 'x' 

### ISSUE THREAD

**Issue by michaeltlu** [akanimax/pro_gan_pytorch#14]
Thanks for publishing this code. I'm getting an error message while running the demo.py code described in the README. I'm using pytorch 1.0.0

For this line of code:

shower = plt.imshow(get_image(start_point))

I get the following error message: forward() missing 1 required positional argument: 'x' 

Any ideas on the cause?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-d122e7e814aa> in <module>
----> 1 shower = plt.imshow(get_image(start_point))

<ipython-input-5-d0c26d67fa7f> in get_image(point)
      1 # function to generate an image given a latent_point
      2 def get_image(point):
----> 3     img = gen(point, depth=depth, alpha=1).detach().squeeze(0).permute(1, 2, 0)
      4     img = (img - img.min()) / (img.max() - img.min())
      5     return img.cpu().numpy()

~/anaconda3/envs/pro_gan_pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/envs/pro_gan_pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    141             return self.module(*inputs[0], **kwargs[0])
    142         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 143         outputs = self.parallel_apply(replicas, inputs, kwargs)
    144         return self.gather(outputs, self.output_device)
    145 

~/anaconda3/envs/pro_gan_pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py in parallel_apply(self, replicas, inputs, kwargs)
    151 
    152     def parallel_apply(self, replicas, inputs, kwargs):
--> 153         return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
    154 
    155     def gather(self, outputs, output_device):

~/anaconda3/envs/pro_gan_pytorch/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py in parallel_apply(modules, inputs, kwargs_tup, devices)
     81         output = results[i]
     82         if isinstance(output, Exception):
---> 83             raise output
     84         outputs.append(output)
     85     return outputs

~/anaconda3/envs/pro_gan_pytorch/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py in _worker(i, module, input, kwargs, device)
     57                 if not isinstance(input, (list, tuple)):
     58                     input = (input,)
---> 59                 output = module(*input, **kwargs)
     60             with lock:
     61                 results[i] = output

~/anaconda3/envs/pro_gan_pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

TypeError: forward() missing 1 required positional argument: 'x'

**Comment by akanimax** [comment]
Hi @michaeltlu,

You're welcome. 
This seems to be a bug on PyTorch's end. As you notice, after the 2nd trace, the error stack lies entirely in torch's space. Anyway, I have tested this demo with `torch 1.0.0` and `python 3.6.5`.
1.) Could you try to setup this environment with python 3.6 interpreter?
Please let me know if 3.6 doesn't work.

Best regards,
@akanimax

**Comment by michaeltlu** [comment]
Great thanks it works with pytorch 1.0 and python 3.6. I had the error with python 3.7.

**Comment by akanimax** [comment]
@michaeltlu,

You're welcome. I am glad to be of help.
Btw, I didn't see this issue open on either the PyTorch discussion forums or on the Repo.
Would you like to report it as bug for PyTorch with python 3.7?

Best regards,
@akanimax
